### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Glusk** [Glusk/sprouts#153]
Bug in [v.0.8.0](https://github.com/Glusk2/sprouts/tree/v0.8.0)
![new bug](https://user-images.githubusercontent.com/8526099/66616746-51d3b800-ebd2-11e9-9a23-acf282cbda6f.png)

**Comment by Glusk2** [comment]
This happens because of the order of events when drawing a move:

1. When a *Move* is completed, it turns blue, however it is not added to the combinatorial representation (to the current *Graph*)
2. Then the game waits for the user to click on the highlighted *Move* to select the middle sprout
3. The middle sprout splits the *Move* from (1.) into two *Moves* and adds them to the combinatorial
   representation. If a sprout, which was added in (2.), is too close to or if it intesersects the cobweb, the game **will not** detect the intersection and the cobweb will not get torn.
